---
- name: restart nginx
  service: name=nginx state=restarted enabled=yes

- name: reload nginx
  service: name=nginx state=reloaded

- name: restart php-fpm
  service: name=nginx state=restarted enabled=yes

- name: reload php-fpm
  service: name=nginx state=reloaded
